public class cTin_Env {
    
    public static Map<String, String> ContractToContractFormFieldMap = new Map<String, String>{
        'Name'=>'Name',
        'OwnerId'=>'OwnerId',
        'cTin_AntiBriberyClause__c'=>'cTin_AntiBriberyClause__c',
        'cTin_CharacterOfSourcing__c'=>'cTin_CharacterOfSourcing__c',
       /* 'cTin_ContractSegment__c'=>'cTin_ContractSegment__c',*/
        'Status__c'=>'cTin_ContractStatus__c',
        'cTin_CRClause__c'=>'cTin_CRClause__c',
        'CurrencyIsoCode'=>'CurrencyIsoCode',
        'cTin_DataPrivacyClause__c'=>'cTin_DataPrivacyClause__c',
        'cTin_DocumentExecution__c'=>'cTin_DocumentExecution__c',
        'cTin_ExitPlan__c'=>'cTin_ExitPlan__c',
        'cTin_FinancialCheck__c'=>'cTin_FinancialCheck__c',
        'cTin_IFCRelevant__c'=>'cTin_IFCRelevant__c',
        'cTin_CriticalityRating__c'=>'cTin_CriticalityRating__c', //mra cpm changes 27/4
        'cTin_LiabilityClause__c'=>'cTin_LiabilityClause__c',
        'cTin_CRClause__c'=>'Sustainability_Clause__c',//mra cpm changes 27/4
        'cTin_CompleteDescription__c'=>'Complete_Description__c',//mra cpm changes 27/4
        'cTin_MainAPCL0__c'=>'cTin_MainAPCL0__c',//mra cpm changes 27/4
        'cTin_MainAPCL1__c'=>'cTin_MainAPCL1__c',//mra cpm changes 27/4
        'cTin_MainAPCL2__c'=>'cTin_MainAPCL2__c',
        'cTin_MainAPCL3__c'=>'cTin_MainAPCL3__c',
        'cTin_OutsourcingCriticalityAssessment__c'=>'cTin_OutsourcingCriticalityAssessment__c',//mra cpm changes 27/4
        'cTin_Compliance_Clause__c'=>'cTin_Compliance_Clause__c',//mra cpm changes 27/4
        'cTin_VRFCriticality__c'=>'cTin_VRFCriticality__c',//mra cpm changes 27/4
        'cTin_MaterialityRating__c'=>'cTin_MaterialityRating__c',
        'cTin_NoticePeriodForTermination__c'=>'cTin_NoticePeriodForTermination__c',
        'cTin_OutsourcingStandards__c'=>'cTin_OutsourcingStandards__c',
        'cTin_PaymentTerms__c'=>'cTin_PaymentTerms__c',
        'cTin_FairTransparentSelectionProcess__c'=>'cTin_RationalOfSupplierSselectionIs__c',
        'cTin_RiskAssessment__c'=>'cTin_RiskAssessment__c',
        'cTin_SavingsType__c'=>'cTin_SavingsType__c',
        'cTin_SupplierAcceptsUNGlobalCompact__c'=>'cTin_SupplierCompliesWithUNGlobalCompact__c',
        'cTin_TerminationClause__c'=>'cTin_TerminationDisputeClause__c',
        'cTin_TypeOfDocument__c'=>'cTin_TypeOfDocument__c',
        'cTin_SpecificTerms__c'=>'cTin_SpecificTerms__c',
        'cTin_GeographicalScope__c'=>'cTin_GeographicalScope__c',
        'cTin_OrganizationalScope__c'=>'cTin_OrganizationalScope__c',
        'cTin_SourcingDecision__c'=>'cTin_SourcingDecision__c',
        'cTin_Requester__c'=>'cTin_Requester__c',
        'cTin_MainReason__c'=>'cTin_MainReason__c',
        'cTin_Analysis__c'=>'cTin_Analysis__c',
        'cTin_AreSingleSourcingRisksIdentified__c'=>'cTin_AreSingleSourcingRisksIdentified__c',
        'cTin_BargainingPower__c'=>'cTin_BargainingPower__c'
    };
}