/**
 * <b>Class EROStatusConfig </b>: will store the information about EROStatusConfig.
 * @author Eric Wartelle
 * @version 1.0
 */
public with sharing class EROStatusConfig {
	//Attributs for the class EROStatusConfig
	public String name { get; set; }
    public Boolean mustBeDisplayed{ get; set; }

	//Constructors for the class EROStatusConfig
	public EROStatusConfig() {
		
	}

	//Methods for the class EROStatusConfig
}